# Generated by Django 5.2.1 on 2025-06-12 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='score',
            field=models.SmallIntegerField(default=0),
        ),
    ]
