# Generated by Django 5.2.7 on 2025-11-08 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_company_about_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='slug',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
