# Generated by Django 5.2.7 on 2025-11-17 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_company_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='score',
            field=models.FloatField(default=0),
        ),
    ]
