# Generated by Django 5.2.7 on 2025-12-11 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_taskqueue'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='legal_status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='origin_country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='parent_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='branches', to='api.company'),
        ),
        migrations.AddField(
            model_name='company',
            name='registration_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
